"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  Play, CheckCircle2, SkipForward, Clock, AlertTriangle, Plus, Pencil, Trash2,
  X, BookOpen, Zap, ShieldAlert,
} from "lucide-react";
import type { TimetableCategory, TimetableDayType, TimetableState } from "@/lib/game-types";
import {
  categoryDef, formatBlockTime, blockStartMinutes, blockEndMinutes,
  blockDurationMinutes, isSleepTime, STUDY_SUBJECTS, CATEGORY_DEFS, TIMETABLE_XP,
} from "@/lib/game-engine/content/timetable";
import {
  setBlockStateAction, addBlockAction, editBlockAction, deleteBlockAction, logStudyAction,
} from "@/app/(app)/timetable/actions";

export interface ClientBlock {
  id: string;
  order: number;
  startHour: number;
  startMin: number;
  endHour: number;
  endMin: number;
  activity: string;
  category: TimetableCategory;
  xpReward: number;
  dayType: TimetableDayType;
  state: TimetableState;
  /** Reason recorded when today's state is EXCUSED. */
  excuseReason?: string;
}

// Static Tailwind classes per category (template-literal class names can't be
// generated by Tailwind's JIT, so map to full literals here).
const CATEGORY_TEXT: Record<TimetableCategory, string> = {
  STUDY: "text-arc-blue",
  EXERCISE: "text-success",
  MORNING_ROUTINE: "text-arc-violet",
  BATH: "text-arc-cyan",
  BREAKFAST: "text-rank-gold",
  LUNCH: "text-rank-gold",
  DINNER: "text-rank-gold",
  GAMING: "text-arc-violet",
  BREAK: "text-slate-400",
  SLEEP: "text-slate-500",
  WORK: "text-arc-cyan",
  COMMUTE: "text-slate-400",
  NETWORKING: "text-arc-violet",
};

const STATE_STYLE: Record<TimetableState, { chip: string; label: string }> = {
  UPCOMING: { chip: "text-slate-400 border-white/10 bg-white/[0.03]", label: "UPCOMING" },
  ACTIVE: { chip: "text-arc-cyan border-arc-cyan/40 bg-arc-cyan/10", label: "ACTIVE" },
  COMPLETED: { chip: "text-success border-success/40 bg-success/10", label: "COMPLETED" },
  MISSED: { chip: "text-danger border-danger/40 bg-danger/10", label: "MISSED" },
  SKIPPED: { chip: "text-slate-400 border-white/10 bg-white/[0.03]", label: "SKIPPED" },
  PAUSED: { chip: "text-rank-gold border-rank-gold/40 bg-rank-gold/10", label: "PAUSED" },
  LATE: { chip: "text-danger border-danger/30 bg-danger/[0.06]", label: "LATE" },
  FINISHED_EARLY: { chip: "text-arc-blue border-arc-blue/40 bg-arc-blue/10", label: "EARLY" },
  EXCUSED: { chip: "text-rank-gold border-rank-gold/40 bg-rank-gold/10", label: "EXCUSED" },
};

const DAY_TABS: { value: Exclude<TimetableDayType, "ALL">; param: string; label: string }[] = [
  { value: "OFFICE", param: "office", label: "Office" },
  { value: "WFH", param: "wfh", label: "WFH" },
  { value: "WEEKEND", param: "weekend", label: "Weekend" },
];

function nowMinutes(d: Date) {
  return d.getHours() * 60 + d.getMinutes() + d.getSeconds() / 60;
}

export function TimetableBoard({
  initialBlocks,
  dayType,
}: {
  initialBlocks: ClientBlock[];
  dayType: Exclude<TimetableDayType, "ALL">;
}) {
  const router = useRouter();
  const [blocks, setBlocks] = useState<ClientBlock[]>(initialBlocks);
  const [now, setNow] = useState<Date>(() => new Date());
  const [editing, setEditing] = useState(false);
  const [editBlock, setEditBlock] = useState<ClientBlock | null>(null);
  const [showAdd, setShowAdd] = useState(false);
  const [studyFor, setStudyFor] = useState<ClientBlock | null>(null);
  const [excuseFor, setExcuseFor] = useState<ClientBlock | null>(null);
  const [, startTransition] = useTransition();

  // Live tick for the countdown / current-block detection.
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(id);
  }, []);

  const mins = nowMinutes(now);
  const current = useMemo(
    () => blocks.find((b) => mins >= blockStartMinutes(b) && mins < blockEndMinutes(b)) ?? null,
    [blocks, mins],
  );

  const overtime = useMemo(() => {
    if (!current) return null;
    if (current.state === "ACTIVE" && mins >= blockEndMinutes(current)) {
      return Math.floor(mins - blockEndMinutes(current));
    }
    return null;
  }, [current, mins]);

  function applyLocalState(id: string, state: TimetableState, excuseReason?: string) {
    setBlocks((prev) =>
      prev.map((b) => (b.id === id ? { ...b, state, excuseReason } : b)),
    );
  }

  function mutateState(id: string, state: TimetableState, reason?: string) {
    applyLocalState(id, state, state === "EXCUSED" ? reason : undefined);
    startTransition(async () => {
      try {
        await setBlockStateAction({ blockId: id, state, reason });
      } catch {
        /* keep optimistic local state; server revalidate will reconcile */
      }
    });
  }

  if (isSleepTime(now) && !editing) {
    return (
      <div className="flex flex-col items-center gap-3 py-16 text-center">
        <div className="text-4xl">🌙</div>
        <p className="font-display text-lg text-slate-200">Sleep Mode</p>
        <p className="max-w-xs text-sm text-slate-500">
          It&apos;s outside your active hours (5 AM – 11 PM). Recovery is part of the climb — rest now.
        </p>
        <button className="btn-ghost mt-2" onClick={() => setEditing(true)}>
          Edit schedule anyway
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Day-type switcher */}
      <div className="flex items-center gap-1 rounded-xl border border-white/[0.06] bg-white/[0.02] p-1">
        {DAY_TABS.map((tab) => (
          <button
            key={tab.value}
            className={`flex-1 rounded-lg px-3 py-1.5 font-display text-xs font-semibold uppercase tracking-wider transition ${
              dayType === tab.value
                ? "border border-arc-cyan/40 bg-arc-cyan/10 text-arc-cyan"
                : "border border-transparent text-slate-500 hover:text-slate-300"
            }`}
            onClick={() => router.push(`/timetable?day=${tab.param}`)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Current task hero */}
      <CurrentTaskCard block={current} now={now} />

      {/* Overtime */}
      {overtime !== null && current && (
        <div className="flex items-center gap-3 rounded-xl border border-danger/40 bg-danger/10 px-4 py-3">
          <AlertTriangle className="h-5 w-5 shrink-0 text-danger" />
          <div className="text-sm">
            <p className="font-display font-semibold text-danger">TIME OVERRUN DETECTED</p>
            <p className="text-slate-400">
              &ldquo;{current.activity}&rdquo; ended at {formatBlockTime(current.endHour, current.endMin)} ·{" "}
              <span className="text-danger">{overtime} min over</span>
            </p>
          </div>
          <button className="btn-ghost ml-auto" onClick={() => mutateState(current.id, "COMPLETED")}>
            Complete
          </button>
        </div>
      )}

      {/* Toolbar */}
      <div className="flex items-center justify-between">
        <span className="sys-label">{blocks.length} blocks</span>
        <div className="flex gap-2">
          {editing && (
            <button className="btn-primary" onClick={() => setShowAdd(true)}>
              <Plus className="h-4 w-4" /> Add
            </button>
          )}
          <button className="btn-ghost" onClick={() => setEditing((e) => !e)}>
            <Pencil className="h-4 w-4" /> {editing ? "Done" : "Edit"}
          </button>
        </div>
      </div>

      {/* Timeline */}
      <div className="space-y-2">
        {blocks.map((b) => (
          <TimelineRow
            key={b.id}
            block={b}
            isCurrent={current?.id === b.id}
            editing={editing}
            onStart={() => mutateState(b.id, "ACTIVE")}
            onComplete={() => mutateState(b.id, "COMPLETED")}
            onSkip={() => mutateState(b.id, "SKIPPED")}
            onExcuse={() => setExcuseFor(b)}
            onLogStudy={() => setStudyFor(b)}
            onEdit={() => setEditBlock(b)}
            onDelete={() => {
              setBlocks((prev) => prev.filter((x) => x.id !== b.id));
              startTransition(() => {
                void deleteBlockAction({ blockId: b.id }).catch(() => {});
              });
            }}
          />
        ))}
      </div>

      {(showAdd || editBlock) && (
        <BlockModal
          block={editBlock}
          viewDayType={dayType}
          onClose={() => {
            setShowAdd(false);
            setEditBlock(null);
          }}
          onSaved={(saved) => {
            setBlocks((prev) => {
              const rest = prev.filter((x) => x.id !== saved.id);
              return [...rest, saved].sort((a, z) => blockStartMinutes(a) - blockStartMinutes(z));
            });
            setShowAdd(false);
            setEditBlock(null);
          }}
        />
      )}

      {studyFor && (
        <StudyTrackerModal
          block={studyFor}
          onClose={() => setStudyFor(null)}
          onLogged={() => {
            applyLocalState(studyFor.id, "COMPLETED");
            setStudyFor(null);
          }}
        />
      )}

      {excuseFor && (
        <ExcuseModal
          block={excuseFor}
          onClose={() => setExcuseFor(null)}
          onExcused={(reason) => {
            mutateState(excuseFor.id, "EXCUSED", reason);
            setExcuseFor(null);
          }}
        />
      )}
    </div>
  );
}

function CurrentTaskCard({ block, now }: { block: ClientBlock | null; now: Date }) {
  if (!block) {
    return (
      <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-6 text-center">
        <p className="sys-label mb-1">Current Task</p>
        <p className="text-slate-400">No block scheduled for {formatBlockTime(now.getHours(), now.getMinutes())}.</p>
      </div>
    );
  }
  const mins = nowMinutes(now);
  const total = blockDurationMinutes(block);
  const elapsed = Math.min(total, Math.max(0, mins - blockStartMinutes(block)));
  const remaining = Math.max(0, blockEndMinutes(block) - mins);
  const pct = total > 0 ? Math.min(100, (elapsed / total) * 100) : 0;
  const def = categoryDef(block.category);
  const remH = Math.floor(remaining / 60);
  const remM = Math.floor(remaining % 60);

  return (
    <div className="rounded-2xl border border-arc-blue/20 bg-arc-blue/[0.04] p-6 shadow-glow">
      <div className="flex items-start justify-between">
        <div>
          <p className="sys-label mb-1">Current Task</p>
          <h2 className="font-display text-xl font-bold text-slate-100">{block.activity}</h2>
          <p className="mt-1 text-sm text-slate-500">
            {formatBlockTime(block.startHour, block.startMin)} – {formatBlockTime(block.endHour, block.endMin)} ·{" "}
            <span className={CATEGORY_TEXT[block.category]}>{def.label}</span>
          </p>
        </div>
        <div className="text-right">
          <p className="font-mono text-2xl font-bold text-arc-cyan">
            {remH > 0 ? `${remH}h ` : ""}{remM}m
          </p>
          <p className="sys-label">remaining</p>
        </div>
      </div>
      <div className="mt-4 h-2 w-full overflow-hidden rounded-full bg-white/[0.06]">
        <div
          className="h-full rounded-full bg-gradient-to-r from-arc-blue-dim via-arc-blue to-arc-cyan shadow-glow transition-[width] duration-1000 ease-linear"
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

function TimelineRow({
  block, isCurrent, editing, onStart, onComplete, onSkip, onExcuse, onLogStudy, onEdit, onDelete,
}: {
  block: ClientBlock;
  isCurrent: boolean;
  editing: boolean;
  onStart: () => void;
  onComplete: () => void;
  onSkip: () => void;
  onExcuse: () => void;
  onLogStudy: () => void;
  onEdit: () => void;
  onDelete: () => void;
}) {
  const def = categoryDef(block.category);
  const st = STATE_STYLE[block.state];
  const excused = block.state === "EXCUSED";
  const done =
    block.state === "COMPLETED" ||
    block.state === "FINISHED_EARLY" ||
    block.state === "SKIPPED" ||
    excused;

  return (
    <div
      className={`flex items-center gap-3 rounded-xl border px-4 py-3 transition ${
        excused
          ? "border-rank-gold/25 bg-rank-gold/[0.04] opacity-70"
          : isCurrent
            ? "border-arc-cyan/40 bg-arc-cyan/[0.05]"
            : "border-white/[0.06] bg-white/[0.02]"
      }`}
    >
      <div className="w-20 shrink-0">
        <p className="font-mono text-xs text-slate-300">{formatBlockTime(block.startHour, block.startMin)}</p>
        <p className="font-mono text-[10px] text-slate-600">{formatBlockTime(block.endHour, block.endMin)}</p>
      </div>

      <div className="min-w-0 flex-1">
        <p className="truncate font-medium text-slate-100">{block.activity}</p>
        <div className="mt-1 flex flex-wrap items-center gap-2">
          <span className={`chip border ${st.chip}`}>{st.label}</span>
          <span className={`chip border border-white/10 ${CATEGORY_TEXT[block.category]}`}>{def.label}</span>
          {block.xpReward > 0 && (
            <span className="chip flex items-center gap-1 border border-rank-gold/30 text-rank-gold">
              <Zap className="h-3 w-3" /> {block.xpReward} XP
            </span>
          )}
        </div>
        {excused && block.excuseReason && (
          <p className="mt-1 truncate text-xs italic text-rank-gold/80" title={block.excuseReason}>
            Excused: {block.excuseReason}
          </p>
        )}
      </div>

      <div className="flex shrink-0 items-center gap-1.5">
        {editing ? (
          <>
            <button className="btn-ghost px-2" onClick={onEdit} aria-label="Edit block">
              <Pencil className="h-4 w-4" />
            </button>
            <button className="btn-ghost px-2 text-danger" onClick={onDelete} aria-label="Delete block">
              <Trash2 className="h-4 w-4" />
            </button>
          </>
        ) : (
          <>
            {!done && block.state !== "ACTIVE" && (
              <button className="btn-primary" onClick={onStart} aria-label="Start block">
                <Play className="h-4 w-4" /> Start
              </button>
            )}
            {block.state === "ACTIVE" && block.category === "STUDY" && (
              <button className="btn-violet" onClick={onLogStudy}>
                <BookOpen className="h-4 w-4" /> Log
              </button>
            )}
            {block.state === "ACTIVE" && (
              <button className="btn-primary" onClick={onComplete} aria-label="Complete block">
                <CheckCircle2 className="h-4 w-4" />
              </button>
            )}
            {!done && (
              <button className="btn-ghost px-2" onClick={onSkip} aria-label="Skip block">
                <SkipForward className="h-4 w-4" />
              </button>
            )}
            {!done && (
              <button
                className="btn-ghost px-2 text-rank-gold"
                onClick={onExcuse}
                aria-label="Excuse block"
                title="Raise an exception — excuse this block with a reason"
              >
                <ShieldAlert className="h-4 w-4" />
              </button>
            )}
            {done && <Clock className="h-4 w-4 text-slate-600" />}
          </>
        )}
      </div>
    </div>
  );
}

// ── Add / Edit modal ──────────────────────────────────────────────
const DAY_TYPE_OPTIONS: { value: TimetableDayType; label: string }[] = [
  { value: "ALL", label: "Every day" },
  { value: "OFFICE", label: "Office" },
  { value: "WFH", label: "WFH" },
  { value: "WEEKEND", label: "Weekend" },
];

function BlockModal({
  block, viewDayType, onClose, onSaved,
}: {
  block: ClientBlock | null;
  viewDayType: Exclude<TimetableDayType, "ALL">;
  onClose: () => void;
  onSaved: (b: ClientBlock) => void;
}) {
  const [activity, setActivity] = useState(block?.activity ?? "");
  const [category, setCategory] = useState<TimetableCategory>(block?.category ?? "STUDY");
  const [dayType, setDayType] = useState<TimetableDayType>(block?.dayType ?? viewDayType);
  const [start, setStart] = useState(
    block ? `${pad(block.startHour)}:${pad(block.startMin)}` : "06:00",
  );
  const [end, setEnd] = useState(block ? `${pad(block.endHour)}:${pad(block.endMin)}` : "07:00");
  const [busy, setBusy] = useState(false);

  async function save() {
    setBusy(true);
    const [sh, sm] = parseHM(start);
    const [eh, em] = parseHM(end);
    const payload = {
      order: sh * 60 + sm,
      startHour: sh, startMin: sm, endHour: eh, endMin: em,
      activity: activity.trim() || "Untitled",
      category,
      xpReward: TIMETABLE_XP[category],
      dayType,
    };
    try {
      if (block) {
        const saved = await editBlockAction({ blockId: block.id, updates: payload });
        onSaved({ ...block, ...payload, id: saved.id });
      } else {
        const saved = await addBlockAction(payload);
        onSaved({ ...payload, id: saved.id, state: "UPCOMING" });
      }
    } finally {
      setBusy(false);
    }
  }

  return (
    <Modal title={block ? "Edit Block" : "Add Block"} onClose={onClose}>
      <label className="sys-label">Activity</label>
      <input className="tt-input" value={activity} onChange={(e) => setActivity(e.target.value)} placeholder="Study Session" />

      <label className="sys-label mt-3">Category</label>
      <select className="tt-input" value={category} onChange={(e) => setCategory(e.target.value as TimetableCategory)}>
        {CATEGORY_DEFS.map((c) => (
          <option key={c.code} value={c.code}>{c.label}</option>
        ))}
      </select>

      <label className="sys-label mt-3">Day Type</label>
      <select className="tt-input" value={dayType} onChange={(e) => setDayType(e.target.value as TimetableDayType)}>
        {DAY_TYPE_OPTIONS.map((d) => (
          <option key={d.value} value={d.value}>{d.label}</option>
        ))}
      </select>

      <div className="mt-3 flex gap-3">
        <div className="flex-1">
          <label className="sys-label">Start</label>
          <input type="time" className="tt-input" value={start} onChange={(e) => setStart(e.target.value)} />
        </div>
        <div className="flex-1">
          <label className="sys-label">End</label>
          <input type="time" className="tt-input" value={end} onChange={(e) => setEnd(e.target.value)} />
        </div>
      </div>

      <button className="btn-primary mt-5 w-full justify-center" disabled={busy} onClick={save}>
        {busy ? "Saving…" : "Save Block"}
      </button>
    </Modal>
  );
}

// ── Excuse ("raise an exception") modal ───────────────────────────
function ExcuseModal({
  block, onClose, onExcused,
}: {
  block: ClientBlock;
  onClose: () => void;
  onExcused: (reason: string) => void;
}) {
  const [reason, setReason] = useState("");
  const trimmed = reason.trim();

  return (
    <Modal title="Raise Exception" onClose={onClose}>
      <p className="text-sm text-slate-400">
        Excuse &ldquo;{block.activity}&rdquo; for a rare, valid reason. No XP is awarded, but it
        won&apos;t count as missed or skipped.
      </p>

      <label className="sys-label mt-4">Reason</label>
      <textarea
        className="tt-input h-20 resize-none"
        value={reason}
        maxLength={300}
        placeholder="e.g. Doctor's appointment"
        onChange={(e) => setReason(e.target.value)}
      />
      <p className="mt-1 text-right font-mono text-[10px] text-slate-600">{trimmed.length}/300</p>

      <button
        className="btn-primary mt-4 w-full justify-center"
        disabled={trimmed.length === 0}
        onClick={() => onExcused(trimmed)}
      >
        <ShieldAlert className="h-4 w-4" /> Excuse Block
      </button>
    </Modal>
  );
}

// ── Study tracker modal ───────────────────────────────────────────
function StudyTrackerModal({
  block, onClose, onLogged,
}: {
  block: ClientBlock;
  onClose: () => void;
  onLogged: () => void;
}) {
  const [subject, setSubject] = useState<string>(STUDY_SUBJECTS[0]);
  const [duration, setDuration] = useState(blockDurationMinutes(block));
  const [deepWork, setDeepWork] = useState(7);
  const [distractions, setDistractions] = useState(0);
  const [notes, setNotes] = useState("");
  const [busy, setBusy] = useState(false);
  const estXp = Math.round(duration * 1.5 * Math.max(0.2, deepWork / 10 - distractions * 0.02));

  async function submit() {
    setBusy(true);
    try {
      await logStudyAction({
        blockId: block.id,
        subject,
        durationMinutes: duration,
        deepWorkScore: deepWork,
        distractions,
        notes,
        missionLinked: "Today's GATE Mission",
      });
      onLogged();
    } finally {
      setBusy(false);
    }
  }

  return (
    <Modal title="Study Tracker" onClose={onClose}>
      <label className="sys-label">Subject</label>
      <select className="tt-input" value={subject} onChange={(e) => setSubject(e.target.value)}>
        {STUDY_SUBJECTS.map((s) => (
          <option key={s} value={s}>{s}</option>
        ))}
      </select>

      <label className="sys-label mt-3">Duration (min)</label>
      <input type="number" className="tt-input" value={duration} min={0} max={600}
        onChange={(e) => setDuration(Number(e.target.value))} />

      <label className="sys-label mt-3">Deep Work Score: <span className="text-arc-cyan">{deepWork}/10</span></label>
      <input type="range" min={1} max={10} value={deepWork} className="w-full accent-arc-blue"
        onChange={(e) => setDeepWork(Number(e.target.value))} />

      <label className="sys-label mt-3">Distractions</label>
      <input type="number" className="tt-input" value={distractions} min={0} max={200}
        onChange={(e) => setDistractions(Number(e.target.value))} />

      <label className="sys-label mt-3">Notes</label>
      <textarea className="tt-input h-20 resize-none" value={notes} onChange={(e) => setNotes(e.target.value)} />

      <div className="mt-4 flex items-center justify-between rounded-lg border border-rank-gold/30 bg-rank-gold/10 px-3 py-2">
        <span className="sys-label text-rank-gold">Estimated XP</span>
        <span className="font-mono font-bold text-rank-gold">+{estXp}</span>
      </div>

      <button className="btn-primary mt-4 w-full justify-center" disabled={busy} onClick={submit}>
        {busy ? "Logging…" : "Log Session"}
      </button>
    </Modal>
  );
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 sm:items-center sm:p-4" onClick={onClose}>
      <div
        className="panel-glow max-h-[90vh] w-full max-w-md overflow-y-auto rounded-t-2xl p-5 sm:rounded-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-4 flex items-center justify-between">
          <h3 className="font-display text-lg font-semibold text-slate-100">{title}</h3>
          <button className="text-slate-500 hover:text-slate-200" onClick={onClose} aria-label="Close">
            <X className="h-5 w-5" />
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

function pad(n: number) {
  return n.toString().padStart(2, "0");
}

function parseHM(value: string): [number, number] {
  const [h, m] = value.split(":");
  return [Number(h) || 0, Number(m) || 0];
}
